
/*
* Copyright (C) 2014 The Android Open Source Project
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
* This file is automatically generated. DO NOT MODIFY!!"
*/

#ifndef ART_COMPILER_SHA_VERSION_H_
#define ART_COMPILER_SHA_VERSION_H_

#define SHA_ART_VERSION "9a9b3092e0b47999609e98962ab1a197c10e79dc3d2bb355463b19c6ac3e4c2bba140c137b4d1af1c360e917169eb8e3c6a01307c923670ea03941d200728c49"
#endif  // ART_COMPILER_SHA_VERSION_H_
